#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr &
"$HOME"/.local/bin/startup.sh
/usr/lib/polkit-1/polkitd &
eww open topbar &

bspc monitor -d 0000 0001 0010 0011 0100 0101 0110 0111 1000 1001

# Light
normal="#c9b9a7"
accent="#c9b9a7"

# Dark
# normal="#3a3124"
# accent="#db930d"

bspc config presel_feedback_color 	$accent
bspc config focused_border_color 	$accent
bspc config normal_border_color 	$normal

bspc config window_gap          	10
bspc config split_ratio         	0.52

bspc config borderless_monocle  	true
bspc config gapless_monocle     	false
bspc config single_monocle      	false

bspc config focus_follows_pointer 	true
bspc config pointer_modifier      	mod4
bspc config pointer_action1       	resize_corner

bspc rule -a Code 					desktop='^1'
bspc rule -a firefox 				desktop='^2'
bspc rule -a Spotify 				desktop='^3'
bspc rule -a vesktop 				desktop='^4'
bspc rule -a Gthumb 				desktop='^5'
bspc rule -a Syncthing 				desktop='^5'

bspc rule -a feh 					state=floating
bspc rule -a Zathura 				state=tiled
bspc rule -a Cpupower-gui 			state=floating
bspc rule -a Lxappearance 			state=floating

# "$HOME"/.config/bspwm/border_on_focused.sh &
"$HOME"/.config/bspwm/border_on_floating.sh &
