#!/bin/bash

# Set decoration geometry
berryc border_width 6
berryc inner_border_width 6
berryc title_height 0
berryc edge_gap 10 74 10 10
berryc edge_lock false

# Text
berryc draw_text false
berryc set_font "Maple Mono-10"
berryc decorate_new true

## Swamp Dark
bgc="242015"
normal="3a3124"
accent="db930d"
textMain="242015"
textOther="db930d"

## Swamp Light
bgc="F1E3D1"
normal="c9b9a7"
accent="c9b9a7"

# Set decoration colors
berryc focus_color         $bgc
berryc unfocus_color       $bgc
berryc inner_focus_color   $accent
berryc inner_unfocus_color $normal 
berryc text_focus_color    $textMain
berryc text_unfocus_color  $textOther

# Other options
berryc smart_place "true"
berryc focus_follows_pointer "false"

# Desktop names
berryc name_desktop 0 "a"
berryc name_desktop 1 "b"
berryc name_desktop 2 "c"
berryc name_desktop 3 "d"
berryc name_desktop 4 "e"
berryc name_desktop 5 "f"
berryc name_desktop 6 "g"
berryc name_desktop 7 "h"
berryc name_desktop 8 "i"
berryc name_desktop 9 "j"

# Start sxhkd and other programs
sxhkd -c "$HOME"/.config/berry/sxhkdrc &
"$HOME"/.local/bin/common_apps.sh
"$HOME"/.config/polybar/scripts/launch.sh &
